### ISSUE TITLE
UI bug when changing search term from invalid to valid word

### ISSUE THREAD

**Issue by philippschuetz** [Fearless09/Dictionary#1]
When searching for an invalid word e.g. "aaaa" it shows "No Definitions Found for 'aaaa'". When you now change the search term from "aaaa" to a valid word like 'cat' it still shows "No Definitions Found for 'cat'". The UI only updates if you hit return or click on the search button after entering a valid word.

**Comment by Fearless09** [comment]
Thanks for the feedback, I’ll see to it

**Comment by Fearless09** [comment]
I really appreciate your feedback on this project and the bug has been fixed
